name: server
channels:
  - pysces
  - defaults
  - conda-forge
  - https://repo.anaconda.com/pkgs/main
  - https://repo.anaconda.com/pkgs/r
dependencies:
  - pip
  - python=3.10
  - pysces
  # - pymem3dg
  - readdy
  - pip:
      - h5py
      - process-bigraph
      - simulariumio
      - smoldyn
      - biosimulators-copasi
      - biosimulators-tellurium
      - biosimulators-pysces
      - copasi-basico
      - tellurium
      - amici
prefix: /opt/conda/envs/server